/**
 * The helper `jj` runs as its diff editor.
 *
 * The extension lives inside Hunk's process, but `jj` only accepts an external
 * program, so the selection has to cross a process boundary. It crosses as
 * data: the extension writes the finished content into a staging directory,
 * and this script — which contains no selection logic at all — copies it into
 * `$right`. Everything that could be subtly wrong stays in TypeScript, where
 * it is unit-tested.
 *
 * `sh` is the one interpreter a machine running `jj` can be assumed to have.
 */
export const HELPER_SCRIPT_NAME = "apply.sh";

export const WRITE_MANIFEST = "write.list";
export const DELETE_MANIFEST = "delete.list";
export const RESTORE_MANIFEST = "restore.list";
export const CONTENT_DIRECTORY = "files";

export const HELPER_SCRIPT = `#!/bin/sh
# Generated by the hunk-commit extension. Applies one prepared selection to
# the directory jj reads a diff edit back from.
set -eu

left="$1"
right="$2"
stage="$3"

# A symlink is unlinked before it is written to or copied over. Redirection
# and cp both resolve the destination, so either would write *through* a link
# in $right to wherever it points, outside the directory jj gave us. Written
# as a function so set -e does not trip over a false test, the way a
# test-and-rm one-liner would when the test fails.
unlink_if_symlink() {
  if [ -L "$1" ]; then
    rm -f "$1"
  fi
}

# Replace content by redirection rather than by copying: it leaves the file's
# existing mode alone, so an executable bit survives being rewritten.
while IFS= read -r path; do
  [ -n "$path" ] || continue
  mkdir -p "$right/$(dirname "$path")"
  unlink_if_symlink "$right/$path"
  cat "$stage/${CONTENT_DIRECTORY}/$path" > "$right/$path"
done < "$stage/${WRITE_MANIFEST}"

while IFS= read -r path; do
  [ -n "$path" ] || continue
  rm -f "$right/$path"
done < "$stage/${DELETE_MANIFEST}"

while IFS= read -r path; do
  [ -n "$path" ] || continue
  if [ -e "$left/$path" ]; then
    mkdir -p "$right/$(dirname "$path")"
    unlink_if_symlink "$right/$path"
    cp -p "$left/$path" "$right/$path"
  else
    rm -f "$right/$path"
  fi
done < "$stage/${RESTORE_MANIFEST}"
`;

/**
 * Paths reach the helper through newline-delimited manifests, so a path
 * containing a newline cannot be expressed. Such paths are legal on POSIX and
 * vanishingly rare; staging refuses them rather than mangling them.
 */
export function isExpressiblePath(path: string): boolean {
  return path !== "" && !path.includes("\n") && !path.includes("\r");
}
